// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7rJAiC7Sw4-2NfnhIN82jo3fTcFC4yZk',
    appId: '1:108661249360:web:308ca5ea57a9085319c855',
    messagingSenderId: '108661249360',
    projectId: 'codesnippy-71bb5',
    authDomain: 'codesnippy-71bb5.firebaseapp.com',
    storageBucket: 'codesnippy-71bb5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm5b3Y0IfQDJyM7FadLeK-HSc-sicvxkI',
    appId: '1:108661249360:android:67b2ea9ccd4d979c19c855',
    messagingSenderId: '108661249360',
    projectId: 'codesnippy-71bb5',
    storageBucket: 'codesnippy-71bb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrrWAELwdFITVqXWhceNHF4TFh2ZVou7A',
    appId: '1:108661249360:ios:306de29bf1cc89f919c855',
    messagingSenderId: '108661249360',
    projectId: 'codesnippy-71bb5',
    storageBucket: 'codesnippy-71bb5.appspot.com',
    androidClientId: '108661249360-n2rhf60opv8rf53va3mk4bkp3qo6mdfq.apps.googleusercontent.com',
    iosClientId: '108661249360-ibkcn9q0bi4mr530dm0vd5pe9967bbja.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeSnippetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrrWAELwdFITVqXWhceNHF4TFh2ZVou7A',
    appId: '1:108661249360:ios:306de29bf1cc89f919c855',
    messagingSenderId: '108661249360',
    projectId: 'codesnippy-71bb5',
    storageBucket: 'codesnippy-71bb5.appspot.com',
    androidClientId: '108661249360-n2rhf60opv8rf53va3mk4bkp3qo6mdfq.apps.googleusercontent.com',
    iosClientId: '108661249360-ibkcn9q0bi4mr530dm0vd5pe9967bbja.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeSnippetsApp',
  );
}
